version: '2'

services:
  php:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-php
    working_dir: /var/www/server
    env_file: './src/.env.example'
    depends_on:
      - mysql
    tty: true
    volumes:
      - ./src:/var/www/server
    ports:
      - "9000:9000"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: task-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/server
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: task-mysql
    restart: unless-stopped
    tty: true
    ports:
      -  "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    container_name: task-redis
    restart: always
    tty: true
    networks:
      - laravel
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  supervisord:
    user: root
    build:
      context: .
      dockerfile: supervisord.Dockerfile
    container_name: task-supervisord
    tty: true
    depends_on:
      - php
      - nginx
    volumes:
      - ./src:/var/www/server
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local